import { z } from "zod";

export const insertSurveyResponseSchema = z.object({
  fullName: z.string().optional().nullable(),
  stageName: z.string().optional().nullable(),
  personalEmail: z.string().optional().nullable(),
  creatorTypeSelf: z.string().optional().nullable(),
  hasManager: z.number().int().optional().nullable(),
  managerName: z.string().optional().nullable(),
  companyName: z.string().optional().nullable(),
  companyEmail: z.string().optional().nullable(),
  creatorType: z.string(),
  currentPlatforms: z.string(),
  ratingPayouts: z.number().int().optional().nullable(),
  ratingAnalytics: z.number().int().optional().nullable(),
  ratingFanManagement: z.number().int().optional().nullable(),
  ratingScheduling: z.number().int().optional().nullable(),
  ratingMessaging: z.number().int().optional().nullable(),
  ratingPaymentProcessing: z.number().int().optional().nullable(),
  ratingOnboarding: z.number().int().optional().nullable(),
  ratingMobileApp: z.number().int().optional().nullable(),
  commentPayouts: z.string().optional().nullable(),
  commentAnalytics: z.string().optional().nullable(),
  commentFanManagement: z.string().optional().nullable(),
  commentScheduling: z.string().optional().nullable(),
  commentMessaging: z.string().optional().nullable(),
  commentPaymentProcessing: z.string().optional().nullable(),
  commentOnboarding: z.string().optional().nullable(),
  commentMobileApp: z.string().optional().nullable(),
  overallScore: z.number().int().optional().nullable(),
  biggestPainPoint: z.string().optional().nullable(),
  mostWantedFeature: z.string().optional().nullable(),
  additionalComments: z.string().optional().nullable(),
  wouldJoinBeta: z.number().int().optional().nullable(),
  email: z.string().optional().nullable(),
});
export type InsertSurveyResponse = z.infer<typeof insertSurveyResponseSchema>;
